name: Deploy library

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release-package:
    if: github.repository == 'ABI-Software/mbfxml2ex'
    runs-on: ubuntu-24.04
    name: Release package
    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Release Python package
        uses: hsorby/release-python-package-action@v1
        with:
          pypi-package-name: mbfxml2ex
